---
name: Experimental Test Release

on:
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  release:
    uses:
      ./.github/workflows/_test_release.yml
    with:
      working-directory: libs/experimental
    secrets: inherit
