---
name: libs/community Release

on:
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  release:
    uses:
      ./.github/workflows/_release.yml
    with:
      working-directory: libs/community
    secrets: inherit
