---
name: libs/langchain Release

on:
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  release:
    uses:
      ./.github/workflows/_release.yml
    with:
      working-directory: libs/langchain
    secrets: inherit

  # N.B.: It's possible that PyPI doesn't make the new release visible / available
  #       immediately after publishing. If that happens, the docker build might not
  #       create a new docker image for the new release, since it won't see it.
  #
  #       If this ends up being a problem, add a check to the end of the `_release.yml`
  #       workflow that prevents the workflow from finishing until the new release
  #       is visible and installable on PyPI.
  release-docker:
    needs:
      - release
    uses:
      ./.github/workflows/langchain_release_docker.yml
    secrets: inherit
