[tool.poetry]
name = "sql-llama2"
version = "0.1.0"
description = "QA with a SQL database using natural language and LLaMA2-13b"
authors = [
    "Lance Martin <lance@langchain.dev>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = "^0.1"
replicate = ">=0.15.4"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.15"

[tool.langserve]
export_module = "sql_llama2"
export_attr = "chain"

[tool.templates-hub]
use-case = "sql"
author = "LangChain"
integrations = ["Replicate"]
tags = ["sql"]

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
