[tool.poetry]
name = "rag-timescale-conversation"
version = "0.1.0"
description = "Conversational RAG using timescale-vector DB as retriver"
authors = [
    "Lance Martin <lance@langchain.dev>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = "^0.1"
openai = "<2"
tiktoken = ">=0.5.1"
pinecone-client = ">=2.2.4"
beautifulsoup4 = "^4.12.2"
python-dotenv = "^1.0.0"
timescale-vector = "^0.0.3"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.15"

[tool.langserve]
export_module = "rag_timescale_conversation"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "Timescale"
integrations = ["OpenAI", "Timescale"]
tags = ["vectordbs"]

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
