# RunPod Project Configuration

title = "placeholder"

[project]
uuid = "placeholder"
name = "placeholder"
base_image = "runpod/base:0.4.4-cuda11.8.0"
gpu_types = ["NVIDIA RTX A4000", "NVIDIA RTX A4500", "NVIDIA RTX A5000", "NVIDIA GeForce RTX 3090", "NVIDIA RTX A6000"]
gpu_count = 1
volume_mount_path = "/runpod-volume"
ports = "8080/http, 22/tcp, 4040/http"
container_disk_size_gb = 10

[project.env_vars]
POD_INACTIVITY_TIMEOUT = "120"
RUNPOD_DEBUG_LEVEL = "debug"
UVICORN_LOG_LEVEL = "warning"

[template]
model_type = "default"
model_name = "None"

[runtime]
python_version = "3.10"
handler_path = "src/handler.py"
requirements_path = "builder/requirements.txt"