[tool.poetry]
name = "neo4j-advanced-rag"
version = "0.1.0"
description = "Balance precise embeddings and context retention with advanced strategies"
authors = [
    "Tomaz Bratanic <tomaz.bratanic@neo4j.com>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = "^0.1"
tiktoken = "^0.5.1"
openai = "<2"
neo4j = "^5.14.0"

[tool.langserve]
export_module = "neo4j_advanced_rag"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "Neo4j"
integrations = ["Neo4j", "OpenAI"]
tags = ["vectordb", "parent", "summarization"]

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
